### PR TITLE
Fix typing in `dArg`

### LINKED ISSUE #8: `dArg` returned types incompatible with `dataclass` fields (VSCode's Pylance issue)
Pylance (PyRight, VS Code) raises a type issue in using `dArg` function

image

### PR DESCRIPTION
**Pull request by diogo-rossi**
Fix #8

### CODE REVIEW

**Comment by konstantinjdobler** [comment]
I will check this out, personally I haven't had this error so far. Unfortunately, these type hints are hard to test for (especially across different type checkers)

**Comment by konstantinjdobler** [comment]
Can you run `black` on your changes? LGTM otherwise.

**Comment by Diogo-Rossi** [comment]
> Can you run `black` on your changes?

Done.

**Comment by konstantinjdobler** [comment]
Thanks!

**Pull request merged**
